export const START_LOGIN_USER = 'START_LOGIN_USER';
export const STOP_LOGIN_USER = 'STOP_LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
