export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';
export const START_CART_PURCHASE = 'START_CART_PURCHASE';
export const STOP_CART_PURCHASE = 'STOP_CART_PURCHASE';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
